image: docker:latest
services:
  - maven:latest


stages:
  - build
  - test
  - package
  - static analysis
  - deploy


variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository
    - target/

build:
  image: maven:latest
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  image: maven:latest
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

static analysis:
  stage: static analysis
  script:
    - mvn spotbugs:check
    - mvn pmd:check
    - mvn jacoco:check


package:
  stage: package
  image: maven:latest
  script:
    - mvn $MAVEN_CLI_OPTS package


deploy develop:
  image: heroku:latest
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS package
    - docker build -t $HEROKU_APP_DEV .
    - docker login -u _ -p $HEROKU_API_KEY registry.heroku.com
    - heroku container:push --app $HEROKU_APP_DEV --context-path . web
    - heroku container:release web --app $HEROKU_APP_DEV
  only:
    - branches
  except:
    - master


deploy master:
  image: heroku:latest
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS package
    - docker build -t $HEROKU_APP .
    - docker login -u _ -p $HEROKU_API_KEY registry.heroku.com
    - heroku container:push --app $HEROKU_APP --context-path . web
    - heroku container:release web --app $HEROKU_APP
  only:
    - master

