image: maven:latest

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository
    - target/

stages:
  - build
  - test
  - package
  - static analysis

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

static analysis:
  stage: static analysis
  script:
    - mvn $MAVEN_CLI_OPTS spotbugs:check pmd:check jacoco:check


package:
  stage: package
  script:
    - mvn $MAVEN_CLI_OPTS package
